version: '3.5'

services:
  easygetapp-react-fe_build:
    build:
      context: .
      dockerfile: Dockerfile.staging
    container_name: 'easygetapp-react-fe_build'
    volumes:
      - easygetapp-react-fe_dist:/code/dist

  easygetapp-react-fe_web:
    image: nginx
    ports:
      - 8001:80
    container_name: 'easygetapp-react-fe_web'
    restart: unless-stopped
    volumes:
      - easygetapp-react-fe_dist:/usr/share/nginx/html:ro
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  easygetapp-react-fe_dist: