version: '3.5'

services:
  easygetapp-react-fe-prod_build:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: 'easygetapp-react-fe-prod_build'
    volumes:
      - easygetapp-react-fe-prod_dist:/code/dist

  easygetapp-react-fe-prod_web:
    image: nginx
    ports:
      - 8001:80
    container_name: 'easygetapp-react-fe-prod_web'
    restart: unless-stopped
    volumes:
      - easygetapp-react-fe-prod_dist:/usr/share/nginx/html:ro
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  easygetapp-react-fe-prod_dist: